Article_Features/urls.py
from django.urls import path

from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.listArticles, name='list-articles'),
    path('create-article', views.createArticle, name='create-article'),
    path('<int:id>', views.articless, name='article'),
]

bmi/urls.py
from django.urls import include, path

from . import views

app_name = 'bmi'

urlpatterns = [
    path('', views.BMIHome, name='BMIHome'),
]

tk1_e06/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('bmi/', include('bmi.urls')),
    path('calories-cal/', include('Calories_Calc.urls')),
    path('to-do-list/', include('ToDoList_Features.urls', namespace='to-do-list')),
    path('articles/', include('Article_Features.urls', namespace='articles')),
    path('bmrcalculator/', include('bmrcalculator.urls'))
]

Article_Features/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from ckeditor.fields import RichTextField

import datetime
# Create your models here.

class Articles(models.Model):
    tittle = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    description = RichTextField(blank=True, null=True)
    image = CloudinaryField('image')
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)


    def __str__(self):
        return '{}'.format(self.tittle)

Article_Features/forms.py
from django import forms
from .models import Articles

class article(forms.ModelForm):
    class Meta:
        model = Articles
        fields = [
            'tittle',
            'author',
            'description',
            'image',
        ]

        labels = {
            'tittle': 'Tittle',
            'author': 'Author',
            'description' : 'Description',
            'image' : 'Image'
        }

        widgets = {
            'tittle' : forms.TextInput(attrs= {'class' : 'form-control', 'style' : 'background-color: #E4E4E4;', 'placeholder' : 'ex: How to increase...',}),
            'author' : forms.TextInput(attrs= {'class' : 'form-control', 'style' : 'background-color: #E4E4E4;', 'placeholder' : 'ex: Sonya Anastasia',}),
            'description' : forms.Textarea(attrs= {'class' : 'form-control',}),
            'image' : forms.FileInput(attrs= {'class' : 'form-contol-file',}),
        }

Article_Features/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django import forms
from django.http import HttpResponse

from cloudinary.forms import cl_init_js_callbacks
from .models import Articles
from .forms import article

def createArticle(request):
  context = dict(backend_form = article)
  if request.method == 'POST':
    form = article(request.POST, request.FILES)
    context['posted'] = form.instance
    if form.is_valid():
        form.save()
        return redirect('articles:list-articles')
  return render(request, 'Article_Features/create-article.html', context)

def listArticles(request):
    articles = Articles.objects.all()
    context = {'articles' : articles}
    return render(request, 'Article_Features/list-articles.html', context)

def articless(request, id):
    arc = Articles.objects.get(id=id)
    context = {'article' : arc}
    return render(request, 'Article_Features/article.html', context)

Article_Features/templates/Article_Features/article.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>{{ article.tittle }}</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
  <div class="container">
      <div class="head">
          <h3 class="tittle-article">{{ article.tittle }}</h3>
          <p class="author-artice">Author: {{ article.author }}</p>
          <p class="date-article">{{ article.create }}</p>
      </div>
      <div>
          <img src="{{ article.image.url }}" class="picture-article">
      </div>
      <div>
          {{ article.description|safe }}
      </div>
  </div>
{% endblock content %}

Article_Features/templates/Article_Features/create-article.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Create Article</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
    {% load cloudinary %}
    <div class="container">
        <h1 class="tittle">Create article</h1>
        <form method="POST" class="form-group" enctype="multipart/form-data">
            {% csrf_token %}
            {{ backend_form.media }}
            <div class="form-group row">
                <label for="{{ backend_form.tittle.id_for_label }}" class="col-sm-2 col-form-label font">Tittle:</label>
                    <div class="col-sm-10">
                        {{ backend_form.tittle }}
                    </div>
            </div>
            <div class="form-group row">
                <label for="{{ backend_form.author.id_for_label }}" class="col-sm-2 col-form-label font">Author:</label>
                    <div class="col-sm-10">
                        {{ backend_form.author }}
                    </div>
            </div>
            <div class="form-group row">
                <label for="{{ backend_form.description.id_for_label }}" class="col-sm-2 col-form-label font">Description:</label>
                    <div class="col-sm-10">
                        {{ backend_form.description }}
                    </div>

            </div>
            <div class="form-group row">
                <label for="{{ backend_form.image.id_for_label }}" class="col-sm-2 col-form-label font">Image:</label>
                    <div class="col-sm-10">
                        {{ backend_form.image }}
                    </div>
            </div>
            <div style="text-align: center">
                <button class= "btn btn-primary" type="submit" style="background-image: linear-gradient(#EC4057, #F57434); border-color: #EC4057">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

Article_Features/templates/Article_Features/list-articles.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Health Articles</title>
    <link rel="stylesheet" href="{% static 'css/style-article.css' %}" type="text/css">
{% endblock meta %}

{% block content %}
  <div class="container">
        <h1 class="tittle">Health Articles</h1>
        {% if articles.count != 0 %}
            <div class="card-deck">
                {% for article in articles %}
                    <div class="col-md-4">
                        <div class="card">
                            <img class="card-img-top" src="{{ article.image.url }}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title"><a href="{% url 'articles:article' article.id %}" class="font-tittle">{{ article.tittle }}</a></h5>
                                <i class="fas fa-user"><small style="margin-left: 5px; font-family: Rubik,sans-serif">{{ article.author }}</small></i><br>
                                <i class="fas fa-calendar-day"><small style="margin-left: 5px; font-family: Rubik,sans-serif">{{ article.create }}</small></i>
                            </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% else %}
            <div style="text-align: center">
                <h4>You haven't added any articles yet</h4>
                <h4>Click icon + to add article</h4>
            </div>
        {% endif %}
        <div style="text-align: center; margin: 10%">
            <a href="{% url 'articles:create-article' %}"><i class="fas fa-plus-circle" id="add"></i></a>
        </div>
    </div>
{% endblock content %}