ToDoList_Features/urls.py
from django.urls import path

from . import views

app_name = 'to-do-list'

urlpatterns = [
    path('', views.createToDo, name='create-todo'),
    path('edit-todo/<str:pk>/', views.editToDo, name='edit-todo'),
    path('delete-todo/<str:pk>/', views.deleteToDo, name='delete-todo'),
]

bmi/urls.py
from django.urls import include, path

from . import views

app_name = 'bmi'

urlpatterns = [
    path('', views.BMIHome, name='BMIHome'),
]

tk1_e06/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('bmi/', include('bmi.urls')),
    path('calories-cal/', include('Calories_Calc.urls')),
    path('to-do-list/', include('ToDoList_Features.urls', namespace='to-do-list')),
    path('articles/', include('Article_Features.urls', namespace='articles')),
    path('bmrcalculator/', include('bmrcalculator.urls'))
]

ToDoList_Features/models.py
from django.db import models

# Create your models here.
class ToDoList(models.Model):
    todo = models.CharField(max_length=100)

    def __str__(self):
        return self.todo

ToDoList_Features/forms.py
from django import forms
from django.forms import ModelForm
from .models import ToDoList

class ToDoForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = [
            'todo',
        ]

        labels = {
            'todo': "Insert your input below"
        }

        widgets = {
            'todo': forms.TextInput(attrs={'placeholder': 'What should I do?'}),
        }

ToDoList_Features/views.py
from django.shortcuts import render, redirect

from django import forms
from django.http import HttpResponse

from .models import ToDoList
from .forms import ToDoForm

# Create your views here.
def createToDo(request):
    if request.method == 'POST':
        form = ToDoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('to-do-list:create-todo')
    
    todos = ToDoList.objects.all()
    print("todos")
    form = ToDoForm()

    context = {'todos':todos, 'form':form}
    return render(request, 'ToDoList_Features/create-todo.html', context)

def editToDo(request, pk):
    todo = ToDoList.objects.get(id=pk)
    form = ToDoForm(instance=todo)

    if request.method == 'POST':
        form = ToDoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('to-do-list:create-todo')

    context = {'form':form}
    return render(request, 'ToDoList_Features/edit-todo.html/', context)

def deleteToDo(request, pk):
    todo = ToDoList.objects.get(id=pk)

    if request.method == 'POST':
        todo.delete()
        return redirect('to-do-list:create-todo')

    context = {'todo':todo}
    return render(request, 'ToDoList_Features/delete-todo.html', context)

ToDoList_Features/templates/ToDoList_Features/create-todo.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>To Do List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        input{
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }
        .btn{
            background-image: linear-gradient(#EC4057, #F57434);
            color: white;
            border-radius: 10px;
            margin-bottom: 5px;
        }
        .card{
            max-width: 50%; text-align: center; 
            background-color: black; color:#ffffff;
            border-radius: 14px;
            margin: auto; margin-bottom: 5%; padding: 3%;
        }
        .item-row{
            text-align: center;
            background-color: white;
            margin-top: 10px; margin-left: 20px; margin-right: 20px;
            border-radius: 10px;
            padding-top: 1%; padding-left: 5%; padding-right: 5%;
            color: black;
        }
    </style>
{% endblock meta %}

{% block content %}

    <!--Jumbotron Image-->
    <div class="jumbotron" style="background-size: cover; background-image: url(/static/img/to-do-jumbotron.jpg);">
        <div style="padding: 20% 3% 3%; color: black;">
            <h5 class="lead" style="font-weight: 500;">List the things you have to do</h5>
            <h2 class="display-4" style="font-weight: 500;">TO-DO LIST</h2>
            <p style="font-weight: 400;">To do list is a list of things that one wants to get done<br>
                or that need to get done. With to-do list, you can<br>
                manage your time better and organize your work and life.</p>
        </div>
    </div>

    <!--To Do List Form-->
    <h1 style="text-align: center; margin-top:5%;">To Do List</h1>
    <div class="card">
        <form method="POST" action="/to-do-list/">
            {% csrf_token %}
            {{form}}
            <button type="submit" class="btn" style="width: 100px; margin-bottom: 5%;">ADD</button>
        </form>

        {% for todo in todos %}
            <div class="item-row" style="color: black;">
                <p>{{todo}}</p>
                <p>
                    <button type="submit" class="btn" style="width: 80px; font-size: smaller;">
                        <a href="{% url 'to-do-list:edit-todo' todo.id %}" style="color: white;">EDIT</a>
                    </button>
                    <button type="submit" class="btn" style="width: 80px; font-size: smaller;">
                        <a href="{% url 'to-do-list:delete-todo' todo.id %}" style="color: white;">DELETE</a>
                    </button>
                </p>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

ToDoList_Features/templates/ToDoList_Features/delete-todo.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Delete To Do</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        input{
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }
        .btn{
            background-image: linear-gradient(#EC4057, #F57434);
            color: white;
            border-radius: 10px;
        }
        .card{
            max-width: 50%; text-align: center; 
            background-color: black; color:#ffffff;
            border-radius: 14px;
            margin: auto; margin-bottom: 5%; padding: 3%;
    </style>
{% endblock meta %}

{% block content %}
    <h1 style="text-align: center; margin-top:5%;">Delete To Do</h1>
    <div class="card">
        <div class="text-center">
            <h5 style="margin-bottom:3%;">Are you sure to delete "{{todo.todo}}"?</h5>
            <button type="submit" class="btn" style="width: 100px;">
                <a href="{% url 'to-do-list:create-todo' %}" style="color: white;">CANCEL</a>
            </button>

            <form method="POST", action="">
                {% csrf_token%}
                <input class="btn btn-info submit" style="width: 100px;" type="submit"  value="CONFIRM">
            </form>
        </div>
    </div>
{% endblock content %}

ToDoList_Features/templates/ToDoList_Features/edit-todo.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
    <title>Edit To Do</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
        input{
            width: 100%;
            padding: 12px 20px;
            margin: 8px 0;
            box-sizing: border-box;
        }
        .btn{
            background-image: linear-gradient(#EC4057, #F57434);
            color: white;
            border-radius: 10px;
        }
        .card{
            max-width: 50%; text-align: center; 
            background-color: black; color:#ffffff;
            border-radius: 14px;
            margin: auto; margin-bottom: 5%; padding: 3%;
        }
    </style>
{% endblock meta %}

{% block content %}
    <h1 style="text-align: center; margin-top:5%;">Change To Do</h1>
        <div class="card">
            <form method="POST", action="">
                {% csrf_token %}
                {{form}}
                <button type="submit" class="btn" style="width: 100px;">APPLY</button>
            </form>
        </div>
{% endblock content %}